services:
  vk_bot_app:
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - main-network
networks:
  main-network:
    driver: 'bridge'