services:
  postgres:
    image: postgres:15
    container_name: BeautyMastersPostgres
    env_file:
      - .env
    entrypoint: /bin/sh -c "apt-get update && apt-get install -y gettext-base && envsubst < /docker-entrypoint-initdb.d/init-db.sql.template > /docker-entrypoint-initdb.d/init-db.sql && docker-entrypoint.sh postgres"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - main-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BeautyMastersVkBotApp
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - main-network
    command: [ "sh", "-c", "npm run migration:run && node dist/main.js" ]
networks:
  main-network:
volumes:
  postgres_data:
