import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchemas1738967778498 implements MigrationInterface {
    name = 'InitialSchemas1738967778498'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."vk_bot_event_event_type_enum" AS ENUM('message_new')`);
        await queryRunner.query(`CREATE TABLE "vk_bot_event" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "event_id" character varying(255) NOT NULL, "event_type" "public"."vk_bot_event_event_type_enum" NOT NULL, "event_api_version" character varying(10) NOT NULL, "message_id" integer NOT NULL, "message_date" integer NOT NULL, "message_from_id" integer NOT NULL, "message_peer_id" integer NOT NULL, "message_payload" character varying(1000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9680071a1632065abe06a1131a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."app_settings_key_enum" AS ENUM('LAST_TS_VALUE')`);
        await queryRunner.query(`CREATE TABLE "app_settings" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" "public"."app_settings_key_enum" NOT NULL, "value" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4800b266ba790931744b3e53a74" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "app_settings"`);
        await queryRunner.query(`DROP TYPE "public"."app_settings_key_enum"`);
        await queryRunner.query(`DROP TABLE "vk_bot_event"`);
        await queryRunner.query(`DROP TYPE "public"."vk_bot_event_event_type_enum"`);
    }

}
